routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// authetication RouteS
//Route::get('registreer', 'PagesController@getRegister');
//Route::get('login', 'PagesController@getLogin');

Route::get('clienten', 'ClientController@Index' );
Route::get('nieuweClient', 'ClientController@create' );

Route::get('panden', 'PandController@Index' );
Route::get('nieuwePand', 'PandController@create' );
Route::get('test', 'PandController@Test' );

Route::get('taxaties', 'TaxatieController@Index' );
Route::get('nieuweTaxatie', 'TaxatieController@create' );

Route::get('inloggen', 'PagesController@getInloggen' );

Route::get('/', 'PagesController@getIndex' );

Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');

Route::resource('client', 'ClientController');
Route::resource('pand', 'PandController');
Route::resource('taxatie', 'TaxatieController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/taxatie.pdf/{id}',  'taxatieController@pdf')->name('taxatie.pdf');

//excel import en export routes van excel maatsites
//Route::get('import-export-csv-excel',array('as'=>'excel.import','uses'=>'FileController@importExportExcelORCSV'));
//Route::post('import-csv-excel',array('as'=>'import-csv-excel','uses'=>'FileController@importFileIntoDB'));
//Route::get('download-excel-file/{type}', array('as'=>'excel-file','uses'=>'FileController@downloadExcelFile'));
Route::post('importNew', 'PandController@pandImportNew')->name('pand.importNew');
Route::post('importNewClient', 'ClientController@ClientImportNewClient')->name('client.importNewClient');

resources/views/taxaties/nieuweTaxatie.blade.php
@extends('layouts.sideNav')

@section('pageName', 'Taxatierapport maken')

@section('titel', 'Taxatierapport maken')

<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>

<script>
  tinymce.init({
    selector: 'textarea',
    menubar: false,  })
</script>

@section('content')
<div class="row">
  <div class="col-md-8">
    <h1>Nieuw taxatierapport maken</h1>
      <p>hier komt een form voor het maken van taxatie rapport afh van het pand met opties enz<br>
      Waarschijnlijk middels een lijst van panden of de optie om een nieuwe toe te voegen via panden handmatig.</p>

      {!! Form::open(array('route' => 'taxatie.store', 'data-parsley-validate' => '', 'files' => true)) !!}

        <div class="row"><div class="col-md-6">
        {{ form::label('clienten_id', 'Client:')}}
        <select class="form-control" name="clienten_id">
          @foreach($clienten as $client)
            <option value="{{$client->id}}">{{$client->voornaam}}</option>
          @endforeach
        </select>
      </div>
      <div class="col-md-6">
        {{ form::label('pand_id', 'Pand:')}}
        <select class="form-control" name="pand_id">
          @foreach($panden as $pand)
            <option value="{{$pand->id}}">{{$pand->straat}}</option>
          @endforeach
        </select>
      </div></div>
        <hr>
        <div class="row">
        <div class="col-md-6">
        {{ form::label('soort_woning', 'Soort:')}}
        <select class="form-control" name="soort_woning">
            <option value="vrijstaande">vrijstaande</option>
            <option value="halfvrijstaande">halfvrijstaande</option>
            <option value="tussengelegen">tussengelegen</option>
            <option value="hoekwoning">hoekwoning</option>
            <option value="appartementsrecht">appartementsrecht</option>
            <option value="galerijflat">galerijflat</option>
            <option value="penthouse">penthouse</option>
            <option value="flatwoning">flatwoning</option>
        </select>
      </div>
<div class="col-md-6">
        {{ form::label('type_woning', 'Type:')}}
        <select class="form-control" name="type_woning">
            <option value="woning">woning</option>
            <option value="villa">villa</option>
            <option value="stadswoning">stadswoning</option>
            <option value="boerderijwoning">boerderijwoning</option>
            <option value="carréboerderij">carréboerderij</option>
        </select>
        </div>
      </div><br>

<div class="row">
        <div class="col-md-4">
        {{ form::label('uitbouw', 'Uitbouw:')}}
        {{ Form::checkbox('omschrijving[]', 'uitbouw', false) }}
        <br>
        {{ form::label('cv', 'Cv:')}}
        {{ Form::checkbox('omschrijving[]', 'cv', true) }}
        <br>
        {{ form::label('berging', 'Berging:')}}
        {{ Form::checkbox('omschrijving[]', 'berging', false) }}
      </div>

      <div class="col-md-4">
      {{ form::label('garage', 'Garage:')}}
      {{ Form::checkbox('omschrijving[]', 'garage', false) }}
      <br>
      {{ form::label('zwembad', 'Zwembad:')}}
      {{ Form::checkbox('omschrijving[]', 'zwembad', false) }}
      <br>
      {{ form::label('schuur', 'Schuur:')}}
      {{ Form::checkbox('omschrijving[]', 'schuur', false) }}
    </div>
    <div class="col-md-4">
    {{ form::label('carport', 'Carport:')}}
    {{ Form::checkbox('omschrijving[]', 'carport', false) }}
    <br>
    {{ form::label('tuin', 'Tuin:')}}
    {{ Form::checkbox('omschrijving[]', 'tuin', true) }}
    <br>
    {{ form::label('invul', 'Invul:')}}
    {{ Form::checkbox('omschrijving[]', 'invul', false) }}
  </div>
</div>

        <hr>
        {{ form::label('hyp4', 'Eigendomsakte:')}}
        <select class="form-control" name="hyp4">
            <option value="1">Beide eigenaar</option>
            <option value="2">Één eigenaar</option>
            <option value="3">Beide eigenaar, een overleden</option>
            <option value="4">Erfgenamen eigenaar</option>
            <option value="5">Gevolmachtigde RechtB</option>
            <option value="6">Cöop Bouwvereniging</option>
            <option value="7">Sitchting, BV of lichaam</option>
        </select>
        <hr>
        {{ form::label('featured_image', 'Upload afbeeling hier')}}
        {{ form::file('featured_image')}}

        {{form:: submit('Taxatie rapport aanmaken', array('class' => 'btn btn-success btn-lg', 'style' => 'margin-top: 10px;'))}}
      {!! Form::close() !!}
  </div>
</div>
@endsection

resources/views/taxaties/rapport.blade.php
<style>
@page { margin: 0px; }
.content {margin: 50px;}
.page-break {page-break-after: always;}
.header {width: 101%; height:150px; background-color:orange; top:-100px;left:-50px;}
.row {display:inline-block;}
.center { margin-left: 20%;}
.afbeelding {height: 400px; width:600px; margin-left: 10%; background-color: #f7f7f7;}
.logo { float:right; padding: 15px; margin-right: 20px;}
h1 {style:none; margin-top:0px; position: absolute; color:white;padding-top:50px;padding-left:40px;font-size: 34;}
ul { list-style-image: url({{ public_path('/img/logowhite.png') }});}
</style>

@php
  $beideEigenaar = "Beide in het kadastraal uittreksel object genoemde personen zijn, ieder voor de onverdeelde helft, eigenaar van het onderhavige object, te weten de grond met opstallen.";
  $eenEigenaar = 'De in het kadastraal uittreksel object genoemde persoon is alleen eigenaar van het onderhavige object, te weten de grond met opstallen. Indien hij/zij een duurzamen huishouding met iemand voert, dient er bij een voorgenomen verkoop, op basis van het Burgerlijk Wetboek, toestemming te worden gegeven door degene waarmee die huishouding wordt gevoerd. Ook als die persoon niet tot de onroerende zaak bevoegd is. Dit omdat het dat het dan gaat om de gezamenlijk bewoonde woning.';
  $eenOverleden = "Beide in het kadastraal uittreksel genoemde personen zijn, ieder voor de onverdeelde helft, eigenaar van het onderhavige object, te weten de grond met opstallen. Een van hen is overleden zodat de ander, alleen of samen met mogelijke erfgenamen (kinderen) bevoegd is tot de eigendom. Omtrend deze bevoegdheid dient de verkopende partij nadere informatie en/of bewijs te verstrekken. (verklaring van erfrecht/testament/volmacht/e.d.)";
  $erfgenaam = "De in het kadastraal uitreksel object genoemde perso(o)n(en) waren eigenaar van het onderhavige object, te weten de grond met opstallen. Door hun overlijden zijn er erfgenamen in hun rechten getreden en derhalve bevoegd. Omtrend de bevoegdheid dient de verkopende partij nadere informatie en/of bewijs te verstrekken. (verklaring van erfrecht/testament/volmacht/e.d.)";
  $gevolmachtigd = "Omdat de eigena(a)r(en) niet meer handelingsbekwaam werden geacht is, middels een rechtelijk bevel, de beschikkingsbevoegdheid over de eigendom van de onroerende zaak bij een gevolmatigde komen te liggen. Hij handelt in deze niet voor zichzelf doch voor de oorspronkelijke eigena(a)r(en). Bij de verkoop van de onroerende zaak dient er, ter bescherming van de rechten van de rechthebbbende, alsnog een rechtelijke goedkeuring te komen. Hierbij toets de rechter de verkoopopbrengts aan een (van te voren) opgesteld taxatierapport van een onafhanelijk taxateur. Eerst na rechtelijke goedkeuring wordt de koopovereenkomst definitief.";
  $coop = "Het eigendomsrecht is hierbij in tweeën geknipt in, enerzijds een blote eigendom en anderzijds een zakelijk gerechtigde. De in het kadastraal uittreksel object genoemde Coöperatieve Bouwvereniging is hierbij de zichtbare blote eigenaar.  Deze blote eigenaar heeft geen rechten tot de onroerende zaak. Hij kan ze niet verkopen of verhuren, noch bewonen, met hypotheek of andere schuld belasten, etc. De bewoner is in deze de zakelijk gerechtigde.  Deze niet zichtbare zakelijk gerechtigde heeft alle rechten zoals die van bewoning, verhuur, verkoop, hypotheek, etc. Alleen hij is (samen met de blote eigenaar) beschikkingsbevoegd. Deze inmiddels in onbruik geraakte constructie werd in de vorige eeuw gebezigd om betaling van de overdrachtsbelasting te omzeilen. Het lek in de Wet is inmiddels gedicht waardoor de Coöperaties langzaam uitsterven.";
  $stichting = "De in het kadastraal uitreksel object genoemde rechtpersoon is eigenaar van het onderhavige object, te weten de grond met opstallen.";

$datum = date("j F Y");
$dagvanweek = date("l");
$arraydag = array("Zondag","Maandag","Dinsdag","Woensdag","Donderdag","Vrijdag","Zaterdag");
$dagvanweek = $arraydag[date("w")];
$arraymaand = array("Januari","Februari","Maart","April","Mei","Juni","Juli","Augustus","September","Oktober","November","December");
$datum = date("j ") . $arraymaand
[date("n") - 1] . date(" Y");

$root= '$_SERVER["DOCUMENT_ROOT"]';
@endphp

<div class="header"><h1>Aankooptaxatie</h1><img class="logo" src="{{ public_path('/img/logowhite.png') }}"/></div><br>
<div class="content">
  <div class="center"><h2>{{ $taxatie->pand['straat']}} {{ $taxatie->pand['huisnummer']}}, {{ $taxatie->pand['postcode']}} {{ $taxatie->pand['plaats']}}</h2></div>
  <img class="afbeelding" src="{{ public_path('/img/taxaties/'. $taxatie->afbeelding) }}" height="400" width="600"/><br>
  </div><br><br><br><br><br><br><br><br><br><br><hr><br>
  <div class="center"> In opdracht van {{ $taxatie->clienten['titel']}} {{ $taxatie->clienten['voorletters']}} {{ $taxatie->clienten['achternaam']}} uitgevoerd op @php echo "d.d. $dagvanweek, $datum";   @endphp</div>

</div>


 <div class="page-break"></div>
 <div class="header"><h1>Inhoudsopgave</h1><img class="logo" src="{{ public_path('/img/logowhite.png') }}"/></div><br>
 <div class="content">
 <h1>Inhoud</h1>
<ul>
<li>1.	Algemeen	3
<li>1.1	De makelaar:	3
<li>1.2	De opdracht:	3
<li>1.3	Het doel:	3
<li>2.	De juridische kaders	4
<li>2.1 Het kadastraal uittreksel object hypotheek 4	4
<li>2.2 De aankomsttitel	6
<li>2.3 Het uittreksel hypotheek 3	8
<li>2.5 De bestemming	8
<li>2.6 De bescherming als Monument	9
<li>2.7 De bodemkwaliteit	9
<li>2.8 Olietank	10
<li>2.9 De Onderaards gangen	10
<li>3.	De intrinsieke kaders:	12
<li>3.1 De ligging	12
<li>3.2 Bouw en constructie	12
<li>3.3 Asbest	13
<li>3.4 De isolatie	14
<li>3.5 De afwerking	14
<li>4.	Onderhoud en gebreken	16
<li>4.1 Het onderhoud en de gebreken	16
<li>4.2 De kosten	26
<li>4.3 De kosten alternatief	26
<li>4.3 De afmetingen	28
<li>5.	De Marktpositie	29
<li>6.	Taxatiekaders:	31
<li>7.	De waarde	32
</div>
<div class="page-break"></div>

<!--pagina 2-->
<div class="header"><h1>1. Algemeen</h1><img class="logo" src="{{ public_path('/img/logowhite.png') }}"/></div><br>
<div class="content">
<h4>BEEK, @php echo "d.d. $dagvanweek, $datum";   @endphp<h4>
<br>

<p><b>1.1	 De makelaar:</b><br>
De heer <b>J.M.E. (Hans) Voorn</b>, beëdigd makelaar in onroerend goed, lid NVM en als gecertificeerd makelaar ingeschreven
in het vastgoedregisters van:<br>
•	Vastgoedcert R´dam kamer Wonen/MKB RMT07.121.2321<br>
Kantoorhoudende aan de <b>Julianalaan 22, 6191 AM BEEK</b>.</p>

<p><b>1.2	 De opdracht:</b><br>
In opdracht van <b>{{ $taxatie->clienten['titel']}} {{ $taxatie->clienten['voorletters']}} {{ $taxatie->clienten['achternaam']}}</b><br>
heeft er op <b>{{ date('j M Y', strtotime($taxatie->created_at)) }}</b> een opname plaatsgevonden van:<br><br>

Het betreft een <b>{{ $taxatie->soort_woning}} {{ $taxatie->type_woning}}</b> met <b>{{ $taxatie->woning_omschrijving}}</b> gelegen
aan de <br><b>{{ $taxatie->pand['straat']}} {{ $taxatie->pand['huisnummer']}}</b> in <b>{{ $taxatie->pand['plaats']}}</b>.<br><br>

<b>Kadastraal bekend als:</b><br>
Gemeente 	: «Gemeente»<br>
Sectie 	: «Sectie»<br>
nummer 	: «NummerAindex»<br>
groot 	: «Grootte_in_m» m²<br>
<!--«voorGem1» 	: «Gemeente1» «voorSec1» 	: «Sectie1» «voorNum1» 	: «NummerAindex1» «voorGroot1» 	: «Grootte_in_m1»
«voorGem2» 	: «Gemeente2» «voorSec2» 	: «Sectie2» «voorNum2» 	: «NummerAindex2» «voorGroot2» 	: «Grootte_in_m2»
			«Totaal_m»--></p>

<p><b>1.3	 Het doel:</b><br>
Het doel van de opname en dit uitgewerkt rapport is het verkrijgen van inzicht in het object, de juridische status, omgevingsfactoren,
 zijn intrinsieke waarden, de bouwtechnische aspecten, de onderhoudskosten en de marktwaarde van het totaal.
 Een en ander in verband met een, door opdrachtgever, te nemen beslissing betreffende een mogelijke aankoop.
</p>
</div>
<div class="page-break"></div>
<!--pagina 3-->
<div class="header"><h1>2.	DE JURIDISCHE KADERS</h1><img class="logo" src="{{ public_path('/img/logowhite.png') }}"/></div><br>
<div class="content">
<p><b>2.1 Het kadastraal uittreksel object hypotheek 4</b><br>
Uit het bijgevoegd uittreksel gaat naar voren dat:<br>
@if ($taxatie->hyp4 == 1)
   {{$beideEigenaar}}
@elseif ($taxatie->hyp4 == 2)
   {{$eenEigenaar}}
@elseif ($taxatie->hyp4 == 3)
   {{$eenOverleden}}
@elseif ($taxatie->hyp4 == 4)
  {{$erfgenaam}}
@elseif ($taxatie->hyp4 == 5)
  {{$gevolmachtigd}}
@elseif ($taxatie->hyp4 == 6)
  {{$coop}}
@elseif ($taxatie->hyp4 == 7)
  {{$stichting}}
@else
 Er is geen geldigde hyp deel 4 optie ingegeven
@endif
</p>

<p><b>2.2 De aankomsttitel</b><br>
⌂ «Aankomsttitel»</p>

<p><b>2.3 De beperkingen van de eigendom</b><br>
⌂ «belemmeringen_alg»</p>

<p>«Bijz_erfdienst_tekst»<br>
⌂ «Bijz_erfdienst_opsom»</p>

<p>«ketting_tekst»<br>
⌂ «Ketting_opsom»</p>

<p>«Kwal_verpl_tekst»<br>
⌂	«Kwal_verpl_opsom»</p>

<p>«kwal_eind_tekst»</p>

<p><b>2.4 Het uittreksel hypotheek 3</b><br>
Uit het bijgevoegd kadastraal uittreksel hypotheken deel 3, blijkt dat het register goed «hyp_3»</p>


<p><b>2.5 De bestemming</b><br>
In het vigerende bestemmingsplan wordt het registergoed aangeduid bestemd te zijn om te gebruiken voor:<br>
⌂	«BP»</p>

<p>«bp_bezwaar»<br>
Indien en voor zover de beoogde bestemming door opdrachtgever afwijkt van de geldende bestemming dan is nader onderzoek bij c.q. overleg met de betreffende gemeente noodzakelijk.</p>
</div>

<div class="page-break"></div>
<!--pagina 4-->
<div class="header"></div>
<div class="content">

 <h1>hypotheken deel 4</h1>
 <p class="lead">
   @if ($taxatie->hyp4 == 1)
      {{$beideEigenaar}}
   @elseif ($taxatie->hyp4 == 2)
      {{$eenEigenaar}}
   @elseif ($taxatie->hyp4 == 3)
      {{$eenOverleden}}
   @elseif ($taxatie->hyp4 == 4)
     {{$erfgenaam}}
   @elseif ($taxatie->hyp4 == 5)
     {{$gevolmachtigd}}
   @elseif ($taxatie->hyp4 == 6)
     {{$coop}}
   @elseif ($taxatie->hyp4 == 7)
     {{$stichting}}
  @else
    Er is geen geldigde hyp deel 4 optie ingegeven
  @endif
 </p>
 </div>
 <div class="page-break"></div>
 <div class="header"></div>
 <div class="content">
 </div>
 pagina 7



 <div class="page-break"></div>
 <div class="header"></div>
 <div class="content">
 </div>
 pagina 8



 <div class="page-break"></div>
 <div class="header"></div>
 <div class="content">
 </div>
pagina 9


 <div class="page-break"></div>
 <div class="header"></div>
 <div class="content">
 </div>

resources/views/taxaties/taxaties.blade.php
@extends('layouts.sideNav')
@section('pageName', 'Taxaties')
@section('titel', 'Taxaties')
@section('content')
  <div class="row">
    <div class="col-md-10">
      <h1>Alle taxatierapporten</h1>
      <p class="lead"> alle rapporten in tabel weergeven</p>
      <br>
    </div>

    <div class="col-md-2">
      <a href="{{ route('taxatie.create')}}" class="btn btn-block btn-primary btn-h1-spacing">Voeg taxatie toe</a>
    </div>

    <div class="col-md-12">
      <hr>
    </div>

  </div>

  <div class="row">
    <div class="col-md-12">

      <div class="table-overzicht">
        @include('layouts.tabel')

        <table id="table" class="table table-hover table-bordered table-striped">
          <thead>
            <tr>
          <th>#</th>
          <th>Straat</th>
          <th>Client</th>
          <th>Woning type</th>
          <th>Aangemaakt</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
          @foreach ($taxaties as $taxatie)
            <tr class='clickable-row' data-href='{{ route('taxatie.show', ['id' => $taxatie->id]) }}'>
              <th> {{ $taxatie ->id}}</th>
              <td> {{ $taxatie->pand['straat'] }} {{$taxatie->pand['huisnummer']}} {{$taxatie->pand['plaats']}}</td>
              <td> {{ $taxatie->clienten['voornaam'] }} {{ $taxatie->clienten['achternaam'] }}</td>
              <th> {{ $taxatie ->soort_woning}} {{ $taxatie ->type_woning}}</th>
              <td> {{ date('j M Y, H:i', strtotime($taxatie->created_at)) }}</td>
              <td> <a href=" {{ route('taxatie.show', $taxatie->id)}}" class="btn btn-default">show</a></td>
              <td> <a href=" {{ route('taxatie.edit', $taxatie->id)}}" class="btn btn-default">edit</a></td>
            </tr>
          @endforeach
        </tbody>
      </table>
      @push('scripts')
        <script>

        $(document).ready(function() {
            var table = $('#table').DataTable();

            $('#table tbody').on('click', 'tr', function () {
                window.location = $(this).data("href");
            } );
        } );
      </script>
      @endpush
    </div>

    </div>
  </div>
@endsection

resources/views/taxaties/wijzigTaxatie.blade.php
@extends('layouts.sideNav')
@section('pageName', 'Wijzig taxatie')
@section('titel', 'Taxatie informatie bijwerken')
@section('content')
<div class="row">
  {!! Form::model($taxatie, ['route' => ['taxatie.update', $taxatie->id], 'method' => 'PUT'] ) !!}
  <div class="col-md-8">
    <h1>Wijzig hier het taxatierapport: {{ $taxatie->titel}}</h1>
      <p class="lead"> Nogmaals het form met alle vragen voor de taxatie die tekst update</p><br>
      <p class="lead">
        {{ form::label('clienten_id', 'Client:') }}
        {{ form::select('clienten_id', $clients, null, ["class" => 'form-control'] ) }}

        {{ form::label('pand_id', 'Pand:')}}
        {{ form::select('pand_id', $pands, null, ["class" => 'form-control'] ) }}

        {{ form::label('soort_woning', 'Soort:')}}
        <select class="form-control" name="soort_woning">
            <option value="vrijstaande" @if ($taxatie->soort_woning == "vrijstaande") selected="selected" @endif>vrijstaande</option>
            <option value="halfvrijstaande" @if ($taxatie->soort_woning == "halfvrijstaande") selected="selected" @endif>halfvrijstaande</option>
            <option value="tussengelegen" @if ($taxatie->soort_woning == "tussengelegen") selected="selected" @endif>tussengelegen</option>
            <option value="hoekwoning" @if ($taxatie->soort_woning == "hoekwoning") selected="selected" @endif>hoekwoning</option>
            <option value="appartementsrecht" @if ($taxatie->soort_woning == "appartementsrecht") selected="selected" @endif>appartementsrecht</option>
            <option value="galerijflat" @if ($taxatie->soort_woning == "galerijflat") selected="selected" @endif>galerijflat</option>
            <option value="penthouse" @if ($taxatie->soort_woning == "penthouse") selected="selected" @endif>penthouse</option>
            <option value="flatwoning" @if ($taxatie->soort_woning == "flatwoning") selected="selected" @endif>flatwoning</option>
        </select>

        {{ form::label('type_woning', 'Type:')}}
        <select class="form-control" name="type_woning">
            <option value="woning" @if ($taxatie->type_woning == "woning") selected="selected" @endif>woning</option>
            <option value="villa" @if ($taxatie->type_woning == "villa") selected="selected" @endif>villa</option>
            <option value="stadswoning" @if ($taxatie->type_woning == "stadswoning") selected="selected" @endif>stadswoning</option>
            <option value="boerderijwoning" @if ($taxatie->type_woning == "boerderijwoning") selected="selected" @endif>boerderijwoning</option>
            <option value="carréboerderij" @if ($taxatie->type_woning == "carréboerderij") selected="selected" @endif>carréboerderij</option>
        </select>

        {{ form::label('hyp4', 'Eigendomsakte:')}}
        <select class="form-control" name="hyp4">
            <option value="1" @if ($taxatie->hyp4 == "1") selected="selected" @endif>Beide eigenaar</option>
            <option value="2" @if ($taxatie->hyp4 == "2") selected="selected" @endif>Één eigenaar</option>
            <option value="3" @if ($taxatie->hyp4 == "3") selected="selected" @endif>Beide eigenaar, een overleden</option>
            <option value="4" @if ($taxatie->hyp4 == "4") selected="selected" @endif>Erfgenamen eigenaar</option>
            <option value="5" @if ($taxatie->hyp4 == "5") selected="selected" @endif>Gevolmachtigde RechtB</option>
            <option value="6" @if ($taxatie->hyp4 == "6") selected="selected" @endif>Cöop Bouwvereniging</option>
            <option value="7" @if ($taxatie->hyp4 == "7") selected="selected" @endif>Sitchting, BV of lichaam</option>
        </select>
      </p>
  </div>

  <div class="col-md-4">
    <div class="well">
      <dl class="dl-horizontal">
        <dt>Client toegevoegd om:</dt>
        <dd>{{ date('j M Y, H:i', strtotime($taxatie->created_at)) }}</dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Laats upgedate:</dt>
        <dd>{{ date('j M Y, H:i', strtotime($taxatie->updated_at)) }}</dd>
      </dl>
      <hr>
      <div class="row">
        <div class="col-sm-6">
          {!! Html::linkRoute('taxatie.show', 'Cancel', array($taxatie->id), array('class' =>'btn btn-danger btn-block' )) !!}
        </div>
        <div class="col-sm-6">
          {{ form::submit('opslaan', ['class' => 'btn btn-success btn-block'])}}
        </div>
      </div>
    </div>
</div>
{!! form::close() !!}
</div>
@endsection