routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// authetication RouteS
//Route::get('registreer', 'PagesController@getRegister');
//Route::get('login', 'PagesController@getLogin');

Route::get('clienten', 'ClientController@Index' );
Route::get('nieuweClient', 'ClientController@create' );

Route::get('panden', 'PandController@Index' );
Route::get('nieuwePand', 'PandController@create' );
Route::get('test', 'PandController@Test' );

Route::get('taxaties', 'TaxatieController@Index' );
Route::get('nieuweTaxatie', 'TaxatieController@create' );

Route::get('inloggen', 'PagesController@getInloggen' );

Route::get('/', 'PagesController@getIndex' );

Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');

Route::resource('client', 'ClientController');
Route::resource('pand', 'PandController');
Route::resource('taxatie', 'TaxatieController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/taxatie.pdf/{id}',  'taxatieController@pdf')->name('taxatie.pdf');

//excel import en export routes van excel maatsites
//Route::get('import-export-csv-excel',array('as'=>'excel.import','uses'=>'FileController@importExportExcelORCSV'));
//Route::post('import-csv-excel',array('as'=>'import-csv-excel','uses'=>'FileController@importFileIntoDB'));
//Route::get('download-excel-file/{type}', array('as'=>'excel-file','uses'=>'FileController@downloadExcelFile'));
Route::post('importNew', 'PandController@pandImportNew')->name('pand.importNew');
Route::post('importNewClient', 'ClientController@ClientImportNewClient')->name('client.importNewClient');

resources/views/panden/nieuwPand.blade.php
@extends('layouts.sideNav')

@section('pageName', 'Pand toevoegen')

@section('titel', 'Pand toevoegen')

@section('content')
<div class="row">
  <div class="col-md-6">
    <h1>Nieuwe Pand toevoegen</h1>
      <p>hier komt een form voor het pand</p>

      {!! Form::open(array('route' => 'pand.store', 'data-parsley-validate' => '')) !!}

        {{form::label('straat', 'Straat:')}}
        {{form::text('straat', null, array('class' => 'form-control', 'required' =>'', 'minlength' =>'2', 'maxlength' =>'50'))}}

        {{form::label('huisnummer', 'Huisnummer:')}}
        {{form::text('huisnummer', null, array('class' => 'form-control', 'required' =>'', 'minlength' =>'2', 'maxlength' =>'25'))}}

        {{form::label('toevoeging', 'Toevoeging:')}}
        {{form::text('toevoeging', null, array('class' => 'form-control'))}}

        {{form::label('postcode', 'Postcode:')}}
        {{form::text('postcode', null, array('class' => 'form-control', 'required' =>'', 'minlength' =>'4', 'maxlength' =>'10'))}}

        {{form::label('plaats', 'Plaats:')}}
        {{form::text('plaats', null, array('class' => 'form-control', 'required' =>'', 'minlength' =>'2', 'maxlength' =>'50'))}}

        {{form::label('huidigePrijs', 'Huidige Prijs:')}}
        {{form::text('huidigePrijs', null, array('class' => 'form-control'))}}

        {{form::label('koopConditie', 'Koop conditie:')}}
        {{form::text('koopConditie', null, array('class' => 'form-control'))}}

        {{form::label('bouwjaar', 'Bouwjaar:')}}
        {{form::text('bouwjaar', null, array('class' => 'form-control'))}}

        {{form:: submit('Pand toevoegen', array('class' => 'btn btn-succes btn-lg', 'style' => 'margin-top: 10px;'))}}
      {!! Form::close() !!}

  </div>
  <div class="col-md-6">
    {!! Form::open(array('route' => 'pand.importNew','method'=>'POST','files'=>'true')) !!}
        <div class="row">
           <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    {!! Form::label('file','Select File to Import:',['class'=>'col-md-3']) !!}
                    <div class="col-md-9">
                    {!! Form::file('file', array('class' => 'form-control')) !!}
                    {!! $errors->first('file', '<p class="alert alert-danger">:message</p>') !!}
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            {!! Form::submit('Upload',['class'=>'btn btn-primary']) !!}
            </div>
        </div>
       {!! Form::close() !!}

  </div>
</div>
@endsection

resources/views/panden/panden.blade.php
@extends('layouts.sideNav')
@section('pageName', 'Panden')
@section('titel', 'Panden')
@section('content')
  <div class="row">
    <div class="col-md-10">
      <h1>Alle Panden weegeven</h1>
      <p class="lead"> alle panden hiero</p>
      <br>
    </div>

    <div class="col-md-2">
      <a href="{{ route('pand.create')}}" class="btn btn-block btn-primary btn-h1-spacing">Voeg pand toe</a>
    </div>

    <div class="col-md-12">
      <hr>
    </div>

  </div>

  <div class="row">
    <div class="col-md-12">

      <div class="table-overzicht">
        @include('layouts.tabel')

        <table id="table" class="table table-hover table-bordered table-striped">
          <thead>
            <tr>
          <th>#</th>
          <th>straat</th>
          <th>huisnummer</th>
          <th>postcode</th>
          <th>plaats</th>
          <th>huidige prijs</th>
          <th>koop conditie</th>
          <th>bouwjaar</th>
        </tr>
        </thead>

        <tbody>
          @foreach ($panden as $pand)
            <tr class='clickable-row' data-href='{{ route('pand.edit', ['id' => $pand->id]) }}'>
              <th> {{ $pand ->id}}</th>
              <td> {{ $pand ->straat}}</td>
              <td> {{ $pand ->huisnummer}}</td>
              <td> {{ $pand ->postcode}}</td>
              <td> {{ $pand ->plaats}}</td>
              <td> {{ $pand ->huidigePrijs}}</td>
              <td> {{ $pand ->koopConditie}}</td>
              <td> {{ $pand ->bouwjaar}}</td>
            </tr>
          @endforeach
        </tbody>
      </table>

      @push('scripts')
        <script>

        $(document).ready(function() {
            var table = $('#table').DataTable();

            $('#table tbody').on('click', 'tr', function () {
                window.location = $(this).data("href");
            } );
        } );
      </script>
      @endpush
    </div>

    </div>
  </div>
@endsection

resources/views/panden/wijzigPand.blade.php
@extends('layouts.sideNav')
@section('pageName', 'Wijzig pand')
@section('titel', 'Pand informatie bijwerken')
@section('content')

  <script>

console.log(111);
function confirmDelete() {
var result = confirm('Are you sure you want to delete?');

if (result) {
return true;
} else {
return false;
}
}

  </script>
<div class="row">
  {!! Form::model($pand, ['route' => ['pand.update', $pand->id], 'method' => 'PUT'] ) !!}
  <div class="col-md-8">
    <h1>Wijzig hier het pand {{ $pand->straat}}</h1>
      <p class="lead"> Hieronder de specifieke client met alle invulvelden uit db realtime aanpassen en updaten</p>
      <p class="lead">
        @foreach($pand->toArray() as $naam => $inhoud)
          <div @if ($loop->first) class="hidden" @endif>
          {{ form::label($naam, ucfirst($naam ).':')}}
          {{ form::text($naam, null, ["class" => 'form-control']) }}
        </div>
        @endforeach

      </p>
  </div>

  <div class="col-md-4">
    <div class="well">
      <dl class="dl-horizontal">
        <dt>Client toegevoegd om:</dt>
        <dd>{{ date('j F Y, H:i', strtotime($pand->created_at)) }}</dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Laats upgedate:</dt>
        <dd>{{ date('j F Y, H:i', strtotime($pand->updated_at)) }}</dd>
      </dl>
      <hr>

      <div class="row">
        <div class="col-sm-6">
          {!! Html::linkRoute('pand.index', 'Cancel', array($pand->id), array('class' =>'btn btn-primary btn-block' )) !!}
        </div>
        <div class="col-sm-6">
          {{ form::submit('opslaan', ['class' => 'btn btn-success btn-block'])}}
        </div>
        {!! form::close() !!}
        <div class="col-sm-6">
          {!! Form::open(['route' => ['pand.destroy', $pand->id], 'method' =>'DELETE', 'onsubmit' => 'return confirmDelete()']) !!}
          {{ Form::submit('Delete', ['class' => 'btn btn-danger btn-block'])}}
          {!! Form::close() !!}
        </div>
      </div>

    </div>
</div>

</div>
@endsection