routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// authetication RouteS
//Route::get('registreer', 'PagesController@getRegister');
//Route::get('login', 'PagesController@getLogin');

Route::get('clienten', 'ClientController@Index' );
Route::get('nieuweClient', 'ClientController@create' );

Route::get('panden', 'PandController@Index' );
Route::get('nieuwePand', 'PandController@create' );
Route::get('test', 'PandController@Test' );

Route::get('taxaties', 'TaxatieController@Index' );
Route::get('nieuweTaxatie', 'TaxatieController@create' );

Route::get('inloggen', 'PagesController@getInloggen' );

Route::get('/', 'PagesController@getIndex' );

Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');

Route::resource('client', 'ClientController');
Route::resource('pand', 'PandController');
Route::resource('taxatie', 'TaxatieController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/taxatie.pdf/{id}',  'taxatieController@pdf')->name('taxatie.pdf');

//excel import en export routes van excel maatsites
//Route::get('import-export-csv-excel',array('as'=>'excel.import','uses'=>'FileController@importExportExcelORCSV'));
//Route::post('import-csv-excel',array('as'=>'import-csv-excel','uses'=>'FileController@importFileIntoDB'));
//Route::get('download-excel-file/{type}', array('as'=>'excel-file','uses'=>'FileController@downloadExcelFile'));
Route::post('importNew', 'PandController@pandImportNew')->name('pand.importNew');
Route::post('importNewClient', 'ClientController@ClientImportNewClient')->name('client.importNewClient');

resources/views/pages/clienten.blade.php
@extends('layouts.sideNav')
@section('pageName', 'Clienten')
@section('titel', 'Clienten')
@section('content')
<div class="row">
  <div class="col-md-10">
    <h1>Alle clienten weegeven</h1>
    <p class="lead"> alle Clienten hiero</p>
    <br>
  </div>

  <div class="col-md-2">
    <a href="{{ route('client.create')}}" class="btn btn-block btn-primary btn-h1-spacing">Voeg client toe</a>
  </div>

  <div class="col-md-12">
    <hr>
  </div>

</div>

<div class="row">
  <div class="col-md-12">

    <div class="table-overzicht" id="tabel">
      @include('layouts.tabel')

      <table id="table" class="table table-hover table-bordered table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Voorletters</th>
            <th>Voornaam</th>
            <th>Tussen</th>
            <th>achternaam</th>
            <th>Adres</th>
            <th>Huis Nr.</th>
            <th>Plaats</th>
            <th>Email</th>
            <th>Mobiel</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($clienten as $client)
            <tr class='clickable-row' data-href='{{ route('client.edit', ['id' => $client->id]) }}'>
              <th> {{ $client ->id}}</th>
              <td> {{ $client ->voorletters}}</td>
              <td> {{ $client ->voornaam}}</td>
              <td> {{ $client ->tussenvoegsels}}</td>
              <td> {{ $client ->achternaam}}</td>
              <td> {{ $client ->adress}}</td>
              <td> {{ $client ->huisnummer}}</td>
              <td> {{ $client ->woonplaats}}</td>
              <td> {{ $client ->email}}</td>
              <td> {{ $client ->mobiel}}</td>
            </tr>
        @endforeach
        </tbody>
      </table>
      @push('scripts')
        <script>

        $(document).ready(function() {
            var table = $('#table').DataTable();

            $('#table tbody').on('click', 'tr', function () {
                window.location = $(this).data("href");
            } );
        } );
      </script>
      @endpush
    </div>



  </div>
</div>

@endsection

resources/views/pages/contact.blade.php
@extends('layouts.sideNav')
@section('pageName', 'Overzicht')
@section('titel', 'Overzicht')
@section('content')
  <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  <script>
    tinymce.init({
      selector: 'textarea',
      menubar: false,  })
  </script>
  <div class="row">
      <div class="col-md-12">
          <h1>Stel hier uw vraag</h1>
          <hr>
          <form action="{{ url('contact') }}" method="POST">
              {{ csrf_field() }}
              <div class="form-group">
                  <label name="email">Email:</label>
                  <input id="email" name="email" class="form-control">
              </div>

              <div class="form-group">
                  <label name="subject">Onderwerp:</label>
                  <input id="subject" name="subject" class="form-control">
              </div>

              <div class="form-group">
                  <label name="message">Vraag of opmerking:</label>
                  <textarea id="message" name="message" class="form-control">Type uw bericht hier...</textarea>
              </div>

              <input type="submit" value="Send Message" class="btn btn-success">
          </form>
      </div>
  </div>

@endsection

resources/views/pages/inloggen.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>
                        <a href="{{ route('register') }}">Register</a>
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Clienten
                </div>
                <p>Hier komen alle clienten met een filter</p>
            </div>
        </div>
    </body>
</html>

resources/views/pages/nieuweClient.blade.php
@extends('layouts.sideNav')

@section('pageName', 'Client toevoegen')

@section('titel', 'Client toevoegen')

@section('content')
<div class="row">
  <div class="col-md-6">
    <h1>Nieuwe Client toevoegen</h1>
      <p>hier komt een form</p>

      {!! Form::open(array('route' => 'client.store', 'data-parsley-validate' => '')) !!}
        {{form::label('geslacht', 'Geslacht:')}}
        {{form::select('geslacht', array('Man' => 'Man', 'Vrouw' => 'Vrouw'))}}
        <br>
        {{form::label('titel', 'Titel:')}}
        {{form::select('titel', array('de heer' => 'de heer', 'mevrouw' => 'mevrouw'))}}
        <br>

        {{form::label('voorletters', 'Voorletters:')}}
        {{form::text('voorletters', null, array('class' => 'form-control'))}}

        {{form::label('voornaam', 'Voornaam:')}}
        {{form::text('voornaam', null, array('class' => 'form-control', 'required' =>'', 'minlength' =>'2', 'maxlength' =>'25'))}}

        {{form::label('tussenvoegsels', 'Tussenvoegsels:')}}
        {{form::text('tussenvoegsels', null, array('class' => 'form-control'))}}

        {{form::label('achternaam', 'Achternaam:')}}
        {{form::text('achternaam', null, array('class' => 'form-control', 'required' =>'', 'minlength' =>'2', 'maxlength' =>'25'))}}

        {{form::label('adress', 'Adress:')}}
        {{form::text('adress', null, array('class' => 'form-control', 'required' =>'', 'minlength' =>'4', 'maxlength' =>'25'))}}

        {{form::label('huisnummer', 'Huisnummer:')}}
        {{form::text('huisnummer', null, array('class' => 'form-control', 'required' =>'', 'minlength' =>'1', 'maxlength' =>'10'))}}

        {{form::label('woonplaats', 'Woonplaats:')}}
        {{form::text('woonplaats', null, array('class' => 'form-control', 'required' =>'', 'minlength' =>'2', 'maxlength' =>'20'))}}

        {{form::label('email', 'Email:')}}
        {{form::text('email', null, array('class' => 'form-control'))}}

        {{form::label('telefoon', 'Telefoon:')}}
        {{form::text('telefoon', null, array('class' => 'form-control'))}}

        {{form::label('mobiel', 'Mobiel:')}}
        {{form::text('mobiel', null, array('class' => 'form-control'))}}

        {{form:: submit('Client toevoegen', array('class' => 'btn btn-succes btn-lg', 'style' => 'margin-top: 10px;'))}}
      {!! Form::close() !!}

  </div>
  <div class="col-md-6">
    {!! Form::open(array('route' => 'client.importNewClient','method'=>'POST','files'=>'true')) !!}
        <div class="row">
           <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    {!! Form::label('file','Select File to Import:',['class'=>'col-md-3']) !!}
                    <div class="col-md-9">
                    {!! Form::file('file', array('class' => 'form-control')) !!}
                    {!! $errors->first('file', '<p class="alert alert-danger">:message</p>') !!}
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            {!! Form::submit('Upload',['class'=>'btn btn-primary']) !!}
            </div>
        </div>
       {!! Form::close() !!}
  </div>
</div>
@endsection

resources/views/pages/wijzigClient.blade.php
@extends('layouts.sideNav')
@section('pageName', 'Wijzig client')
@section('titel', 'Client wijzigen')
@section('content')

  <script>
$(window).on('load',function(){
  console.log(5 + 6);
//CLICK-HANDLERS=============================
    $('.hoofd-item').click(function(){
        var submenu = $(this).parent().children('.subitem');
        if (submenu.css('display') == 'none') {
            $('.subitem').hide(); //first hide any previously showing submenu's
            submenu.show(); //then show the current submenu
        } else {
            submenu.hide(); //hide the current submenu again
        }
    });
});
  console.log(6 + 6);

  //werkt (nog) niet op een of andere manier
$('#inklap').on('click', function() {
    console.log(5 + 6);
  $('.menu-container').toggleClass('clicked');
  $('.container-inhoud').toggleClass('click');
});

console.log(111);
function confirmDelete() {
var result = confirm('Are you sure you want to delete?');

if (result) {
return true;
} else {
return false;
}
}

  </script>
<div class="row">
    {!! Form::model($client, ['route' => ['client.update', $client->id], 'method' => 'PUT'] ) !!}
  <div class="col-md-8">
    <h1>Wijzig hier de client {{ $client->voornaam}}</h1>
      <p class="lead"> Hieronder de specifieke client met alle invulvelden uit db realtime aanpassen en updaten</p>

      <p>@foreach($client->toArray() as $naam => $inhoud)
        <div @if ($loop->first) class="hidden" @endif>
        {{ form::label($naam, ucfirst($naam ).':')}}
        {{ form::text($naam, null, ["class" => 'form-control']) }}
      </div>
      @endforeach</p>
  </div>

  <div class="col-md-4">
    <div class="well">
      <dl class="dl-horizontal">
        <dt>Client toegevoegd om:</dt>
        <dd>{{ date('j M Y, H:i', strtotime($client->created_at)) }}</dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Laats upgedate:</dt>
        <dd>{{ date('j M Y, H:i', strtotime($client->updated_at)) }}</dd>
      </dl>
      <hr>
      <div class="row">
        <div class="col-sm-6">
          {!! Html::linkRoute('client.index', 'Cancel', array($client->id), array('class' =>'btn btn-primary btn-block' )) !!}
        </div>
        <div class="col-sm-6">
          {{ form::submit('opslaan', ['class' => 'btn btn-success btn-block'])}}
        </div>
        {!! form::close() !!}
        <div class="col-sm-6">

          {!! form::open(['route' => ['client.destroy', $client->id], 'method' =>'DELETE', 'onsubmit' => 'return confirmDelete()']) !!}
          {{ form::submit('Delete', ['class' => 'btn btn-danger btn-block'])}}
          {!! form::close() !!}
      </div>
    </div>
</div>

</div>

@endsection